spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native,test

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}

---
spring:
  profiles: test

security:
  user:
    password: 11
    name: user


logging:
  level:
    org.springframework.security: DEBUG
