logging:
  level:
    org.springframework.security: INFO
  config: classpath:logback-spring.xml

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq
  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMP: false

---

spring:
  profiles: test

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.105:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.0.105:5000/uaa/users/current