spring:
  data:
    mongodb:
      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ${MONGO_INITDB_DATABASE}
      port: 27017

server:
  context-path: /uaa
  port: 5000

logging:
  config: classpath:logback.xml