spring:
  data:
    mongodb:
      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ${MONGO_INITDB_DATABASE}
      port: 27017

server:
  context-path: /uaa
  port: 5000


---
spring:
  profiles: test

  data:
    mongodb:
      host: localhost
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: auth
      port: 27017