security:
  oauth2:
    client:
      clientId: market-service
      clientSecret: ${MARKET_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: market-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: market
      port: 27017

server:
  context-path: /market
  port: 8082

chart:
  size: 100


---

spring:
  profiles: test
  data:
    mongodb:
      host: localhost
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: market
      port: 27017

security:
  oauth2:
    client:
      clientId: market-service
      clientSecret: ${MARKET_SERVICE_PASSWORD}
      accessTokenUri: http://192.168.0.105:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

