security:
  oauth2:
    client:
      clientId: prediction-service
      clientSecret: ${STATISTIC_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /prediction
  port: 8090

---

spring:
  profiles: test

security:
  oauth2:
    client:
      clientId: prediction-service
      clientSecret: prediction
      accessTokenUri: http://192.168.0.105:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /prediction
  port: 8090

logging:
  level:
    o.apache.coyote.http11.Http11Processor: warn