version: '2.1'
services:
#для статистики
  elk-statistic:
    image: seko/platform-elkx-sales-statistic
    environment:
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: 343434
      KIBANA_USER: kibana
      KIBANA_PASSWORD: 343434
      LOGSTASH_USER: logstash_system
      LOGSTASH_PASSWORD: 343434
    ports:
      - 5601:5601 # kibana